
name: 'Release & Build'
on:
 push:
    branches:   
      - 'release-**' 
jobs:
  release_and_build:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        tag: '1.0.3'
        artifacts: "myfile.md" 
        prerelease: true
#         token: ${{ secrets.GITHUB_TOKEN }}
